[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
^/(
  (
      \.git
    | docker
    | .+/migrations
    | venv
    | email-log-messages
  )/
  | manage.py
)
'''