# Generated by Django 5.0.3 on 2024-03-23 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "workload",
                    models.CharField(max_length=100, verbose_name="Carga Horária"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
    ]
