# Generated by Django 5.0.3 on 2024-03-21 14:43

import apps.student.models.student
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mother_name", models.CharField(max_length=100, verbose_name="Nome da Mãe")),
                ("father_name", models.CharField(max_length=100, verbose_name="Nome do Pai")),
                ("phone", models.CharField(blank=True, max_length=11, null=True, verbose_name="Telefone")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.address", verbose_name="Endereço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("registration", models.CharField(blank=True, max_length=10, null=True, verbose_name="Matrícula")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=9,
                        verbose_name="Sexo",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Data de Nascimento")),
                ("rg", models.CharField(blank=True, max_length=9, null=True, verbose_name="RG")),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "flie_rg",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.student.models.student.upload_to_rg,
                        verbose_name="Arquivo RG",
                    ),
                ),
                (
                    "file_cpf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.student.models.student.upload_to_cpf,
                        verbose_name="Arquivo CPF",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.parent",
                        verbose_name="Informações dos responsáveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
    ]
