# Generated by Django 5.0.3 on 2024-03-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="flie_rg",
            new_name="file_rg",
        ),
    ]
