# Generated by Django 5.0.3 on 2024-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_flie_rg_student_file_rg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=14, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="student",
            name="rg",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="RG"
            ),
        ),
    ]
