# Generated by Django 5.0.3 on 2024-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_cpf_alter_student_rg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Matrícula"
            ),
        ),
    ]
