# Generated by Django 5.0.3 on 2024-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Matrícula",
            ),
        ),
    ]
