# Generated by Django 5.0.3 on 2024-03-22 21:59

import apps.core.validators.validate_cpf
from django.db import migrations, models
from apps.core.validators import validate_cpf

class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_student_cpf_alter_student_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[validate_cpf],
                verbose_name="CPF",
            ),
        ),
    ]
